// Generated by CoffeeScript 1.9.2
(function() {
  var Document, _;

  _ = require('underscore');

  Document = (function() {
    Document.fromObject = function(object) {
      var doc;
      doc = new Document();
      _.extend(doc, object);
      if (doc.id != null) {
        doc.setMetadataValue("key", doc.id);
      }
      return doc;
    };

    function Document() {
      this.setMetadata({});
    }

    Document.prototype.setMetadata = function(metadata) {
      return this["@metadata"] = metadata;
    };

    Document.prototype.getMetadata = function() {
      return this["@metadata"];
    };

    Document.prototype.getMetadataValue = function(key) {
      return this.getMetadata()[key.toLowerCase()];
    };

    Document.prototype.setMetadataValue = function(key, value) {
      return this.getMetadata()[key.toLowerCase()] = value;
    };

    Document.prototype.setMetadataValues = function(object) {
      var key, results, value;
      results = [];
      for (key in object) {
        value = object[key];
        results.push(this.setMetadataValue(key, value));
      }
      return results;
    };

    return Document;

  })();

  module.exports = Document;

}).call(this);
