// Generated by CoffeeScript 1.4.0
(function() {
  var Document, assert, basicObject, doc, documentOperations, testino;

  testino = require('testino');

  assert = require('assert');

  Document = require('../document');

  basicObject = {
    id: "users/tony",
    name: "Tony Heupel"
  };

  doc = Document.fromObject(basicObject);

  module.exports = documentOperations = testino.createFixture('Document Operations');

  documentOperations.tests = {
    "Document.fromObject result should be the same object with some new properties": function() {
      assert.equal(doc.id, basicObject.id, "Document should have the same id property");
      assert.equal(doc.name, basicObject.name, "Document should have the same name property");
      return assert(doc.getMetadata(), "An instance of Document should have a non-null metadata property");
    },
    "Document.fromObject should add the 'id' property as the '@metadata/Key' property": function() {
      assert(doc.getMetadata(), "metadata should not be null");
      return assert.equal(doc.getMetadataValue("Key"), doc.id);
    }
  };

  if (require.main === module) {
    console.log(module.exports.run());
  }

}).call(this);
